version: '3'

#volumes:
#  devel_db_data: {}
#  devel_db_data_backups: {}

services:

  django: &django
    build:
      context: .
      dockerfile: ./compose/devel/django/Dockerfile
    image: grodt_test_project_devel_django
    container_name: django
    depends_on:
      - mailhog
    volumes:
      - .:/app
    env_file:
      - ./.envs/devel
    ports:
      - "127.0.0.1:8000:8000"
    command: /start

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "127.0.0.1:8025:8025"

  redis:
    image: redis:5.0
    container_name: redis

  celeryworker:
    <<: *django
    image: grodt_test_project_devel_celeryworker
    container_name: celeryworker
    depends_on:
      - redis
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: grodt_test_project_devel_celerybeat
    container_name: celerybeat
    depends_on:
      - redis
      - celeryworker
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: grodt_test_project_devel_flower
    container_name: flower
    depends_on:
      - redis
      - celeryworker
    ports:
      - "127.0.0.1:5555:5555"
    command: /start-flower
